http://localhost:8000/
###
http://localhost:8000/status
###
http://localhost:8000/blocks
###
POST http://localhost:8000/blocks

{
    "message": "Mine Block!!"
}

###
http://localhost:8000/blocks/81f2ced897805e5539e750784e8d12bff104712be9bf8845ce52e006b0f3252e